import { NextResponse } from "next/server";

import prisma from "@/lib/prisma";
import { hashToken } from "@/lib/auth/token";
import { authService } from "@/lib/services/auth.service";
import { userRepository } from "@/lib/repositories/user.repository";
import { passwordResetTokenRepository } from "@/lib/repositories/password-reset-token.repository";
import { AppError } from "@/lib/errors/app-error";
import { logger } from "@/lib/logger";

import {
  rateLimit,
  getClientIp,
  getRetryAfterSeconds,
} from "@/lib/rate-limit";

// ==================================
// RESET PASSWORD
// POST /api/reset-password
// ==================================

export async function POST(
  request: Request
) {
  try {
    // ----------------------------------
    // READ REQUEST
    // ----------------------------------

    const body =
      await request.json();

    const token =
      typeof body.token === "string"
        ? body.token.trim()
        : "";

    const password =
      typeof body.password ===
      "string"
        ? body.password
        : "";

    // ----------------------------------
    // VALIDATE TOKEN
    // ----------------------------------

    if (!token) {
      return NextResponse.json(
        {
          error:
            "This password reset link is invalid.",
        },
        {
          status: 400,
        }
      );
    }

    // Raw token generated by
    // randomBytes(32).toString("hex")
    // contains exactly 64 hex characters.

    if (
      !/^[a-f0-9]{64}$/i.test(
        token
      )
    ) {
      return NextResponse.json(
        {
          error:
            "This password reset link is invalid.",
        },
        {
          status: 400,
        }
      );
    }

    // ----------------------------------
    // VALIDATE PASSWORD
    // ----------------------------------

    if (password.length < 8) {
      return NextResponse.json(
        {
          error:
            "Password must be at least 8 characters.",
        },
        {
          status: 400,
        }
      );
    }

    if (password.length > 128) {
      return NextResponse.json(
        {
          error:
            "Password must be 128 characters or fewer.",
        },
        {
          status: 400,
        }
      );
    }

    // ----------------------------------
    // HASH RECEIVED TOKEN
    // ----------------------------------
    //
    // Used only for the rate-limit key,
    // so the secret token is never
    // stored in the RateLimit table.

    const tokenHash =
      hashToken(token);

    // ==================================
    // RATE LIMIT
    // ==================================
    //
    // Maximum:
    // 5 reset attempts for this
    // IP + reset token combination
    // every 15 minutes.

    const ip =
      getClientIp(request);

    const rateLimitResult =
      await rateLimit({
        key:
          `reset-password:${ip}:${tokenHash}`,

        limit: 5,

        windowMs:
          15 * 60 * 1000,
      });

    // ----------------------------------
    // RATE LIMIT EXCEEDED
    // ----------------------------------

    if (!rateLimitResult.success) {
      const retryAfter =
        getRetryAfterSeconds(
          rateLimitResult.resetAt
        );

      return NextResponse.json(
        {
          error:
            "Too many password reset attempts. Please try again later.",
        },
        {
          status: 429,

          headers: {
            "Retry-After":
              String(retryAfter),
          },
        }
      );
    }

    // ----------------------------------
    // VALIDATE RESET REQUEST
    // ----------------------------------

    const prepared =
      await authService.resetPassword(
        {
          token,
          newPassword: password,
        }
      );

    // ----------------------------------
    // UPDATE PASSWORD + DELETE TOKENS
    // ----------------------------------
    //
    // Both operations happen in the
    // same database transaction.

    await prisma.$transaction([
      userRepository.updatePassword(
        prepared.userId,
        prepared.hashedPassword
      ),

      passwordResetTokenRepository.deleteByEmail(
        prepared.userEmail
      ),
    ]);

    // ----------------------------------
    // SUCCESS
    // ----------------------------------

    return NextResponse.json(
      {
        message:
          "Your password has been reset successfully.",
      },
      {
        status: 200,
      }
    );
  } catch (error) {
    if (error instanceof AppError) {
      return NextResponse.json(
        {
          error: error.message,
          ...error.details,
        },
        {
          status: error.statusCode,
        }
      );
    }

    logger.error(
      "Reset password error",
      error
    );

    return NextResponse.json(
      {
        error:
          "Something went wrong while resetting your password.",
      },
      {
        status: 500,
      }
    );
  }
}
